name: onboarding_overlay
description: Flexible to control Onboarding overlay with or without target element (fork from onboard_overlay)
version: 2.0.1+1
repository: https://github.com/talamaska/onboarding_overlay

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
